# Generated by Django 6.0.6 on 2026-06-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('age_rating', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('poster_url', models.CharField(max_length=300)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
